### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by ghost** [brad811/dart-rpg#5]
Is this project dead?
If this project was ported as a web view to android app.
It would've gotten 10k downloads
Those simple pixel level maker are having lots of downloads in play store

**Comment by brad811** [comment]
Hey, thanks for your interest! I haven't been able to work on this project for a while, but I still really like it, haha.

A mobile editor would be cool! I think it'd have to have its own version of the UI, otherwise everything would be way too tiny to use on your phone. But it would definitely be possible!
